### ISSUE TITLE
Not working

### ISSUE THREAD

**Issue by bondz** [rooftoprafa/f3-falsum#5]
Created a new F3 app, added routes and navigated to an unspecified route, was getting error 500 in console with nothing displayed.

**Comment by rooftoprafa** [comment]
Is your debug variable equals 3?
Have you booted Falsum like in the (small) docs? 

Show me some code so I can understand what could be.
Thanks

**Comment by bondz** [comment]
Yes, looking at it again, I think it's because I changed `cwd`

Mt app is setup like this

    app/
       --- configs/
       --- views/
       --- ....
       --- bootstrap.php
    lib/
       --- base
       --- falsum
    .htaccess
    index.php

In `index.php` I have

    chdir( realpath( __DIR__ . "/app" ) );
    require_once ("bootstrap.php");

In `bootstrap.php`
    //load F3, configure routes and load Falsum in F3 autoload.
    Falsum\Run::handler(true);
    $f3->run();

Navigate to an unspecified route, blank screen, (Error 500 in console)

Using `php 5.5.8` and `Apache 2.4.7`

**Comment by rooftoprafa** [comment]
Its better to load Falsum using composer :/ instead of placing it on F3 Lib folder. 
But that should be working to, use it Capitalize name for the folder, like:

```
lib/
  --- Falsum/
          --- Resources/
          --- Run.php
```

If that is not enought, you may want to change `Falsum\Run::handler(true)` to right after the place where you load you configuration files. If you're not loading any configurations files, place it right after the you create your `$f3` instance.

Hope this helps.

**Comment by bondz** [comment]
I have tried your suggestion, loaded it right after creating the F3 instance and it still does not work. When I tried to install using `composer` with `composer require rooftoprafa/f3-falsum [--dev]`, I get an error 

    [InvalidArgumentException]
    Could not find package rooftoprafa/f3-falsum at any version for your minimum-stability (stable).
    Check the package spelling or your minimum-stability.

Thanks for your time.

**Comment by rooftoprafa** [comment]
Use

```shell
composer require rooftoprafa/f3-falsum
```

instead, widthout the dev part, this will install the last stable version(currently v2.2). Let me know if it dind't work.

**Comment by bondz** [comment]
I meant I tried dev too, and it still didn't work, same error.

**Comment by rooftoprafa** [comment]
I cant understand what is wrong with your code, I've tried on many of my apps and it always worked. Could you please create a git repository or a .zip file so that I can test it on your code? 

Thanks

**Comment by bondz** [comment]
Okay, will do. Thanks.

-----Original Message-----

**Comment by rooftoprafa** [comment]
I found the problem a couple of days ago, try again with the new version please.
Cheers and thank you for your time. :+1:

**Comment by bondz** [comment]
Ooh, yeah, it works now.... Tried to find the fault in your last commit, couldn't exactly pinpoint it.... Can you please summarize what was faulty? 

Thanks for fixing it :D :+1:

**Comment by rooftoprafa** [comment]
Sure,
you can see it here:

https://github.com/rooftoprafa/f3-falsum/commit/661fe75494688e81a96336f1647a0ab589015cd9

**Comment by bondz** [comment]
Okay, got it. Thanks :+1:

**Comment by ptraceur** [comment]
Is it working correctly now?
